import * as THREE from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
const canvas=document.querySelector("#game-canvas"),renderer=new THREE.WebGLRenderer({canvas,antialias:true}),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(58,1,.1,500);
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;scene.background=new THREE.Color(0x75c9ef);scene.fog=new THREE.Fog(0x75c9ef,35,115);camera.position.set(20,15,25);
const controls=new OrbitControls(camera,canvas);controls.target.set(0,0,0);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=4;controls.maxDistance=75;controls.maxPolarAngle=Math.PI*.48;
scene.add(new THREE.HemisphereLight(0xc8efff,0x28502d,2.2));const sun=new THREE.DirectionalLight(0xffefc2,2.5);sun.position.set(20,35,15);scene.add(sun);
new GLTFLoader().load("assets/world/world.gltf",g=>{scene.add(g.scene);document.querySelector("#hint").textContent="Drag to look · Joystick to move · Pinch to zoom"},undefined,()=>document.querySelector("#hint").textContent="World failed to load. Use HTTPS or localhost.");
const move={x:0,y:0,up:false,down:false},pad=document.querySelector("#joystick"),stick=document.querySelector("#stick");let active=null;
function setStick(e){const r=pad.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=37,k=Math.min(1,max/(Math.hypot(dx,dy)||1));move.x=dx/max*k;move.y=dy/max*k;stick.style.transform=`translate(${move.x*max}px,${move.y*max}px)`}
pad.addEventListener("pointerdown",e=>{active=e.pointerId;pad.setPointerCapture(active);setStick(e)});pad.addEventListener("pointermove",e=>{if(e.pointerId===active)setStick(e)});for(const type of ["pointerup","pointercancel"])pad.addEventListener(type,e=>{if(e.pointerId===active){active=null;move.x=move.y=0;stick.style.transform=""}});
for(const [id,key] of [["up","up"],["down","down"]]){const b=document.querySelector(`#${id}`);b.addEventListener("pointerdown",e=>{move[key]=true;b.setPointerCapture(e.pointerId)});for(const type of ["pointerup","pointercancel"])b.addEventListener(type,()=>move[key]=false)}
addEventListener("keydown",e=>{if(["KeyW","ArrowUp"].includes(e.code))move.y=-1;if(["KeyS","ArrowDown"].includes(e.code))move.y=1;if(["KeyA","ArrowLeft"].includes(e.code))move.x=-1;if(["KeyD","ArrowRight"].includes(e.code))move.x=1;if(e.code==="KeyQ")move.up=true;if(e.code==="KeyE")move.down=true});addEventListener("keyup",e=>{if(["KeyW","ArrowUp","KeyS","ArrowDown"].includes(e.code))move.y=0;if(["KeyA","ArrowLeft","KeyD","ArrowRight"].includes(e.code))move.x=0;if(e.code==="KeyQ")move.up=false;if(e.code==="KeyE")move.down=false});
let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000),speed=13*dt,forward=new THREE.Vector3();last=now;camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new THREE.Vector3().crossVectors(forward,camera.up).normalize();for(const p of [camera.position,controls.target]){p.addScaledVector(forward,-move.y*speed);p.addScaledVector(right,move.x*speed);p.y+=(move.up?speed:0)-(move.down?speed:0)}controls.update();renderer.render(scene,camera);requestAnimationFrame(frame)}function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener("resize",resize);resize();requestAnimationFrame(frame);